#!/bin/bash

s=("0-strcat.c" "1-isdigit.c" "1-memcpy.c" "1-strncat.c" "100-atoi.c" "2-strchr.c" "2-strlen.c" "2-strncpy.c" "3-islower.c" "3-puts.c" "3-strcmp.c" "3-strspn.c" "4-isalpha.c" "4-strpbrk.c" "5-strstr.c" "6-abs.c" "9-strcpy.c")
for i in ${s[@]}
do
	file=$(find . -name $i)

	cp $file ~/alx-low_level_programming/0x09-static_libraries
done
